### ISSUE TITLE
mobile version editor has issue

### ISSUE THREAD

**Issue by myworldbox** [metahkg/metahkg#6]
the editor is not well limited in the frame in the phone.
Also, in safari, all threads cannot be shown.

**Comment by sdip15fa** [comment]
fixed in [25a03e6](https://github.com/metahkg/metahkg/commit/25a03e68d149534249c5f79b829797e3bff3e2d7)

**Comment by sdip15fa** [comment]
https://gitlab.com/metahkg/metahkg-web/-/issues/11
